/* Iron Logbook v2. Browser UI; training calculations are shared with the tests. */
(() => {
  'use strict';
  const T=Training,E=EXERCISES,$=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=n=>Number(n).toLocaleString(undefined,{maximumFractionDigits:1});
  const dayLabel=d=>T.date(d).toLocaleDateString(undefined,{weekday:'short',day:'numeric',month:'short'});
  const shortDate=d=>T.date(d).toLocaleDateString(undefined,{day:'numeric',month:'short'});
  const paths={home:'M3 10 12 3l9 7M5 9v11h5v-6h4v6h5V9',calendar:'M8 2v4m8-4v4M4 9h16M5 4h14a1 1 0 0 1 1 1v15H4V5a1 1 0 0 1 1-1M8 13h2m4 0h2m-8 4h2',barbell:'m6 8 10 10M3 9l6-6m6 18 6-6M2 6l4-4m12 20 4-4M7 5l12 12M5 7l12 12',book:'M12 5v16M12 5C8 2 4 3 2 4v15c4-2 7-1 10 2 3-3 6-4 10-2V4c-2-1-6-2-10 1',chart:'M4 3v17h17M7 15l4-5 4 2 5-7',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1 1-3',arrow:'M4 12h16m-6-6 6 6-6 6',left:'m15 6-6 6 6 6',right:'m9 6 6 6-6 6',check:'m5 12 4 4L19 6',clock:'M12 7v5l3 2M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20',play:'m8 5 11 7-11 7V5',pause:'M8 5v14m8-14v14',close:'m6 6 12 12M6 18 18 6',heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8',leaf:'M20 3c-10-1-18 4-14 12 8 5 16-1 14-12M4 21 16 8',scale:'M5 3h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2M7 7q5-4 10 0l-3 4h-4L7 7m5-2v4',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14m5 12 6 6',swap:'M3 7h17m-4-4 4 4-4 4M21 17H4m4-4-4 4 4 4',download:'M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4',shield:'m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6l9-4m-5 10 3 3 7-7',plus:'M12 4v16M4 12h16',star:'m12 2 3 6.5L22 10l-5 5 .8 7-5.8-3.5L6.2 22l.8-7-5-5 7-1.5L12 2',info:'M12 11v6m0-10v1M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20'};
  const icon=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.barbell}"/></svg>`;
  const demo=new URLSearchParams(location.search).get('demo')==='1',storageKey=demo?'ironlog.demo.v4':'ironlog.v2';
  let state=T.defaults(),storageBlocked=false,readFailure=false,route='today',week=T.monday(T.today()),query='',group='All',onlyAvailable=true,favoritesOnly=false,chartExercise='row',coachMode='guidance',activeDate=null,pendingPlan=null,modalOpener=null,animation=null,toastTimeout=null;
  let timer=null,wakeLock=null,audioContext=null;
  try {const saved=localStorage.getItem(storageKey);if(saved)state=T.migrate(JSON.parse(saved));else if(demo)seedDemo();}catch(error){readFailure=true;storageBlocked=true;$('#storage-warning').hidden=false;$('#storage-warning').textContent='Your stored data could not be read. It has been left untouched. Download the original data in Settings before restoring a valid backup.';}
  if(!Object.keys(state.sessions).length)week=T.monday(T.nextPlan(state)?.date||T.today());
  function seedDemo(){
    state.config.setup=true;state.config.name='Alex';state.config.start=T.addDays(T.today(),-35);state.config.experience='experienced';
    for(let i=28;i>0;i--){const d=T.addDays(T.today(),-i),p=T.planAt(state.config,d);if(!p)continue;const s=T.newSession(state,d,p);s.finishedAt=T.date(d).getTime();s.updatedAt=s.finishedAt;s.startedAt=s.finishedAt-40*60000;
      s.snapshot.forEach(e=>{const x=E[e.id];s.exercises[e.id].sets.forEach(set=>Object.assign(set,{w:x.equipment.some(k=>['barbell','dumbbells','legExtension'].includes(k))?String(e.id==='row'||e.id==='bbrdl'?28.7+Math.floor((28-i)/7)*2:e.id==='preach'?12.7:e.id==='goblet'?12:8):'',r:String(e.unit==='seconds'?30:e.range.at(-1)),rir:'2',complete:true}));s.exercises[e.id].done=true;});state.sessions[d]=s;
      const m=d.slice(0,7),day=String(T.date(d).getDate());state.metrics[m]??={month:m,days:{}};state.metrics[m].days[day]={bw:String(82-i*.035),waist:'87',updatedAt:s.finishedAt};
    }
  }
  function save(){
    if(readFailure)return false;
    try{localStorage.setItem(storageKey,JSON.stringify(state));storageBlocked=false;$('#save-status').textContent=demo?'Demo data':'Saved on this device';$('#storage-warning').hidden=true;return true;}
    catch{storageBlocked=true;$('#save-status').textContent='Not saved';$('#storage-warning').hidden=false;$('#storage-warning').textContent='Browser storage is unavailable or full. Keep this page open and download a backup in Settings to keep your changes.';return false;}
  }
  function commit(s){s.updatedAt=Date.now();state.sessions[s.date]=s;save();}
  function toast(text){clearTimeout(toastTimeout);$('#toast').textContent=text;$('#toast').classList.add('show');toastTimeout=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
  function nav(to){if(location.hash==='#'+to)render();else location.hash=to;}
  function title(text,subtitle,action=''){return `<div class="page-heading"><div><h1>${text}</h1><p>${subtitle}</p></div>${action||`<span class="date-chip">${icon('calendar')}${dayLabel(T.today())}</span>`}</div>`;}
  const btn=(text,action,cls='',extra='')=>`<button type="button" class="btn ${cls}" data-action="${action}" ${extra}>${text}</button>`;
  const empty=(heading,copy,action='')=>`<div class="empty">${icon('chart')}<h3>${heading}</h3><p>${copy}</p>${action}</div>`;
  const goalName=()=>({muscle:'Muscle & strength',fatloss:'Fat loss & strength',fitness:'General fitness'}[state.config.goal]);
  const prescription=e=>`${e.target} sets · ${e.range.join('–')} ${e.unit}${E[e.id]?.side?' / side':''}`;
  const equipmentText=id=>E[id].equipment.filter(k=>k!=='safeties').map(k=>({barbell:'Barbell',bench:'Bench',preacher:'Preacher',legExtension:'Leg attachment',dumbbells:'Dumbbells'}[k])).join(' + ')||'Bodyweight';
  function figure(id,phase=0,decorative=false){
    const ex=E[id],d=EXTRA_POSES[ex?.pose]||POSES[ex?.pose||id];if(!d)return '';
    const p=d.a.map((v,i)=>v+(d.b[i]-v)*phase),point=n=>[p[n*2],p[n*2+1]],line=(a,b,w,color)=>`<path d="M${point(a).join(' ')} ${point(b).join(' ')}" stroke="${color}" stroke-width="${w}" stroke-linecap="round"/>`;
    let equipment='';
    if(d.bench){let shape=d.bench===2?'M24 48 65 68h25':d.bench===7?'M26 62h60':id==='pushup'?'M24 75h31':d.bench===8?'M25 64h44':`M24 62h64`;equipment=`<g fill="none" stroke="#9daf9f" stroke-width="4" stroke-linecap="round"><path d="${shape}"/><path d="M31 66v30m48-30v30"/></g>`;}
    if(d.pad)equipment+='<g fill="none" stroke="#97aa9a" stroke-width="4" stroke-linecap="round"><path d="m40 44 30 18M46 70h27m-15 0v26"/></g>';
    const h=point(3),gearType=id==='curl'?'barH':id==='calfBW'?'none':d.gear;
    if(gearType==='barH')equipment+=`<g stroke="#263e32" fill="#263e32"><path d="M${h[0]-24} ${h[1]}h48" stroke-width="3"/><rect x="${h[0]-27}" y="${h[1]-8}" width="5" height="16" rx="1.5"/><rect x="${h[0]+22}" y="${h[1]-8}" width="5" height="16" rx="1.5"/></g>`;
    else if(gearType==='db1'||gearType==='db2')equipment+=`<g fill="#243b30"><rect x="${h[0]-7}" y="${h[1]-3}" width="14" height="6" rx="2"/><rect x="${h[0]-9}" y="${h[1]-7}" width="5" height="14" rx="2"/><rect x="${h[0]+4}" y="${h[1]-7}" width="5" height="14" rx="2"/></g>`;
    if(gearType==='leg')equipment+=`<path d="M68 63 ${p[12]} ${p[13]}" stroke="#8ca48c" stroke-width="4"/><circle cx="${p[12]}" cy="${p[13]}" r="5" fill="#374f40"/>`;
    const limb2=d.a2?d.a2.map((v,i)=>v+(d.b2[i]-v)*phase):[p[10]+7,p[11],p[12]+8,p[13]];
    return `<svg viewBox="0 0 120 106" ${decorative?'aria-hidden="true"':`role="img" aria-label="${esc(ex?.name||id)}: ${phase<.5?'starting':'end'} position, schematic side view"`}><ellipse cx="61" cy="100" rx="45" ry="3" fill="#d3dfce"/><g fill="none"><path d="M${point(4)} ${limb2[0]} ${limb2[1]} ${limb2[2]} ${limb2[3]}" stroke="#718a74" stroke-width="5" stroke-linecap="round"/>${line(4,5,7,'#324b3c')}${line(5,6,5.5,'#c99b77')}${line(1,4,11,'#4a7355')}${line(0,1,4,'#c99b77')}${line(1,2,6,'#537a5c')}${line(2,3,4.5,'#c99b77')}</g><circle cx="${p[0]}" cy="${p[1]}" r="6.5" fill="#c99b77"/><path d="M${p[0]-6} ${p[1]-2}q1-10 11-3" fill="#293d30"/><path d="M${p[12]-2} ${p[13]}h9" stroke="#243a2b" stroke-width="4" stroke-linecap="round"/>${equipment}</svg>`;
  }
  function heroArt(){return `<svg class="hero-art" viewBox="0 0 320 270" aria-hidden="true"><circle cx="208" cy="161" r="112" fill="#d0e7b7"/><circle cx="208" cy="161" r="84" fill="none" stroke="#bfd7a6"/><circle cx="208" cy="161" r="60" fill="none" stroke="#bfd7a6"/><g transform="translate(180 148) rotate(-32)"><rect x="-90" y="-8" width="195" height="16" rx="5" fill="#66845c"/><rect x="-80" y="-38" width="19" height="76" rx="6" fill="#57774e"/><rect x="-60" y="-52" width="29" height="104" rx="9" fill="#264d36"/><rect x="-55" y="-42" width="3" height="82" rx="2" fill="#537c47"/><rect x="47" y="-52" width="29" height="104" rx="9" fill="#264d36"/><rect x="77" y="-38" width="19" height="76" rx="6" fill="#57774e"/><rect x="54" y="-42" width="3" height="82" rx="2" fill="#537c47"/><path d="M-22 0h58" stroke="#91ae7e" stroke-width="6" stroke-linecap="round"/></g><path d="m268 56 3 10 10 3-10 3-3 10-3-10-10-3 10-3z" fill="#6b8c57"/></svg>`;}
  function metric(label,value,note,i){return `<div class="metric"><div class="metric-top">${label}${icon(i)}</div><div class="metric-value">${value}</div><div class="metric-note">${note}</div></div>`;}
  function weekStrip(start){return `<div class="week-strip">${Array.from({length:7},(_,i)=>{const d=T.addDays(start,i),p=T.planAt(state.config,d),s=T.sessionOn(state,d);return `<button class="day ${p?'scheduled':''} ${d===T.today()?'current':''} ${s?.finishedAt?'complete':''}" data-action="day" data-date="${d}" aria-label="${dayLabel(d)} · ${s?.finishedAt?(s.partial?'Finished early':'Completed'):s?'Workout in progress':p?.name||'Recovery day'}"><small>${T.date(d).toLocaleDateString(undefined,{weekday:'short'})}</small><b>${T.date(d).getDate()}</b><span class="day-icon">${icon(s?.finishedAt?'check':p||s?'barbell':'leaf')}</span></button>`;}).join('')}</div><div class="week-key"><span>Planned</span><span>Completed</span><span>Recovery</span></div>`;}
  function learnCard(id,full=false){const ex=E[id];return `<button class="learn-card" data-action="guide" data-id="${id}" aria-label="Learn ${ex.name}"><div class="learn-image">${figure(id,.7,true)}<span class="play-bubble">${icon('play')}</span></div><div class="learn-info">${full?`<span class="badge">${ex.group}</span>`:''}<strong>${ex.name}</strong><small>${full?equipmentText(id):ex.group+' · Movement guide'}</small></div></button>`;}
  function exerciseLine(e){return `<div class="exercise-line"><div class="thumb">${figure(e.id,.6,true)}</div><div><strong>${esc(e.name)}</strong><small>${prescription(e)}</small></div><button class="chevron" data-action="guide" data-id="${esc(e.id)}" aria-label="Learn ${esc(e.name)}">${icon('right')}</button></div>`;}
  function weekSessions(start){return Object.values(state.sessions).filter(s=>s.date>=start&&s.date<T.addDays(start,7)&&s.date<=T.today());}
  function renderToday(){
    const now=T.today(),start=T.monday(now),thisWeek=weekSessions(start),done=thisWeek.filter(s=>s.finishedAt).length,stats=thisWeek.reduce((a,s)=>{const t=T.totals(s);return {sets:a.sets+t.sets,volume:a.volume+t.volume};},{sets:0,volume:0}),weights=T.measurements(state).filter(x=>T.number(x.bw)>0),lastWeight=weights.at(-1),displayWeek=!Object.keys(state.sessions).length?T.monday(T.nextPlan(state)?.date||now):start;
    const unfinished=Object.values(state.sessions).filter(s=>!s.finishedAt).sort((a,b)=>b.date.localeCompare(a.date))[0];
    const next=unfinished?{date:unfinished.date,name:unfinished.name,ex:unfinished.snapshot,key:unfinished.day,tag:'Pick up where you left off'}:T.nextPlan(state);
    const activeAction=unfinished?'resume':'start',extra=unfinished?`data-date="${unfinished.date}"`:next?`data-key="${next.key}"`:'';
    return title(`Let's get stronger${state.config.name?', '+esc(state.config.name):''}.`,'Your plan, your pace. Every session is a step forward.')+
      (!state.config.setup?`<div class="subtle-banner">${icon('settings')}<p><strong>Your home gym is ready.</strong> Four days, general fitness, and your Domyos + Rebel Active equipment.</p><a href="#settings" class="text-link">Fine-tune my plan ${icon('arrow')}</a></div>`:'')+
      `<div class="dashboard-grid"><div class="stack"><section class="hero"><div class="eyebrow">YOUR ROOM. YOUR ROUTINE.</div><h2>Small steps.<br>Stronger you.</h2><p>${T.planAt(state.config,now)?'Your next good session starts here. Follow the plan, learn the movement, and make it yours.':'Recovery is part of getting stronger. Take a breather and get to know your next workout.'}</p>${btn(`${icon(unfinished?'play':'calendar')}${unfinished?'Resume workout':'Explore my weekly plan'} ${icon('arrow')}`,unfinished?'resume':'plan','',extra)}${heroArt()}</section>
      <div class="metric-grid">${metric('This week',`${done}<span>/ ${state.config.days.length}</span>`,'workouts finished','calendar')}${metric('Volume lifted',`${stats.volume>=1000?fmt(stats.volume/1000):fmt(stats.volume)}<span>${stats.volume>=1000?'t':'kg'}</span>`,'completed sets this week','barbell')}${metric('Body weight',lastWeight?`${esc(lastWeight.bw)}<span>kg</span>`:'—',lastWeight?shortDate(lastWeight.date):'Add your first check-in','scale')}</div>
      <section class="card week-card"><div class="section-title"><h2>${displayWeek>start?'Your next week':'Your week'} at a glance</h2><a class="text-link" href="#plan">View plan ${icon('arrow')}</a></div>${weekStrip(displayWeek)}</section>
      <section class="learn-section"><div class="section-title"><h2>Confidence in every rep</h2><a class="text-link" href="#exercises">All exercises ${icon('arrow')}</a></div><div class="library-preview">${['row','legext','goblet'].map(id=>learnCard(id)).join('')}</div></section></div>
      <div class="stack"><section class="card next-workout"><div class="section-title"><span class="eyebrow">${unfinished?'IN PROGRESS':'UP NEXT'}</span><span class="badge">${next?dayLabel(next.date):'All set'}</span></div><h2>${esc(next?.name||'Make time to recover')}</h2><p>${esc(next?.tag||'Your next plan is ready in My plan.')}</p>${next?`<div class="workout-meta"><span>${icon('clock')}~${state.config.duration} min</span><span>${icon('barbell')}${next.ex.length} exercises</span></div>${next.ex.slice(0,3).map(exerciseLine).join('')}<small class="muted">+ ${Math.max(0,next.ex.length-3)} more in your session</small>${btn(`${icon('play')}${unfinished?'Resume workout':'Start workout'} ${icon('arrow')}`,activeAction,'full',extra)}`:''}</section>
      <section class="card coach-card"><div class="coach-top"><div class="coach-symbol">${icon('spark')}</div><div><h3>A note from your coach</h3><small>GUIDANCE FOR YOUR NEXT STEP</small></div></div><h4>${done?'Consistency comes first.':'Start with confidence.'}</h4><p>${done?`You have completed ${done} session${done===1?'':'s'} this week. Keep an eye on how your sets feel, as well as the numbers.`:'Choose a comfortable starting load and leave 2–3 good reps in reserve. Good technique is progress, too.'}</p><a class="text-link" href="#coach">Open my coach ${icon('arrow')}</a></section></div></div>`;
  }
  function renderPlan(){
    const routines=T.routines(state.config),days=Array.from({length:7},(_,i)=>T.addDays(week,i));
    return title('A plan that fits your life.',`${state.config.days.length} sessions per week · ${goalName()} · Around ${state.config.duration} minutes per session`,btn(`${icon('settings')}Edit plan`,'settings','secondary'))+
      `<div class="card"><div class="section-title"><div><span class="eyebrow">WEEKLY PLAN</span><h2 class="spaced" style="margin-top:7px">${shortDate(week)} – ${shortDate(T.addDays(week,6))}</h2></div><div class="button-row"><button class="icon-button" data-action="week-prev" aria-label="Previous week">${icon('left')}</button><button class="text-link" data-action="week-now">This week</button><button class="icon-button" data-action="week-next" aria-label="Next week">${icon('right')}</button></div></div>${weekStrip(week)}</div>
      <div class="plan-grid spaced">${days.filter(d=>T.planAt(state.config,d)||state.sessions[d]).map(d=>{const s=T.sessionOn(state,d),p=s?{name:s.name,ex:s.snapshot,tag:'Your saved workout',key:s.day}:T.planAt(state.config,d);return `<section class="card plan-card"><div class="plan-date">${dayLabel(d)}</div><span class="badge ${s?.finishedAt?'':'gray'}">${s?.finishedAt?(s.partial?'Finished early':'Completed'):s?'In progress':d<T.today()?'Not logged':'Scheduled'}</span><h3>${esc(p.name)}</h3><p>${esc(p.tag)}</p><div class="workout-meta"><span>${icon('barbell')}${p.ex.length} exercises</span><span>${icon('clock')}~${state.config.duration} min</span></div>${p.ex.map(exerciseLine).join('')}${btn(`${s?.finishedAt?'Review session':s?'Resume workout':'Preview workout'} ${icon('arrow')}`,'day','secondary full',`data-date="${d}"`)}</section>`;}).join('')||empty('A fresh start is ahead.','Your plan begins '+dayLabel(state.config.start)+'. Browse the coming week or edit your start date.')}</div>
      <div class="two-col spaced"><section class="card soft"><h3>${icon('leaf')} Room to recover</h3><p class="spaced">On the other days, take an easy walk or do gentle mobility if you feel up to it. You can also simply rest. ${state.config.goal==='fitness'?'Build your everyday activity alongside these strength sessions.':''}</p></section><section class="card"><h3>How this plan progresses</h3><p class="spaced">${state.config.experience==='new'?'Begin with two working sets per movement.':'Three working sets per movement.'} Add controlled reps within the range first. Your coach considers a small weight increase after you reach the top on every set with at least two reps left.</p><a href="#coach" class="text-link">See the reasoning ${icon('arrow')}</a></section></div>`;
  }
  function filteredExercises(){return Object.keys(E).filter(id=>(!onlyAvailable||T.available(id,state.config))&&(group==='All'||E[id].group===group)&&(!favoritesOnly||(state.config.favorites||[]).includes(id))&&(E[id].name+' '+E[id].group+' '+equipmentText(id)).toLowerCase().includes(query.toLowerCase()));}
  function libraryResults(){const ids=filteredExercises();return `<div class="section-title"><p class="muted small">${ids.length} movement guides · Setup, full rep & common mistakes</p></div>${ids.length?`<div class="exercise-grid">${ids.map(id=>learnCard(id,true)).join('')}</div>`:empty('No matching movements.','Try another search or turn off the equipment filter.')}`;}
  function renderLibrary(){return title('Move well. Feel stronger.','A little guidance goes a long way. Learn each exercise before your first set.')+`<div class="search-row"><label class="search-wrap">${icon('search')}<input id="exercise-search" type="search" aria-label="Search exercises" placeholder="Search an exercise, muscle or equipment…" value="${esc(query)}"></label><label class="check-label"><input id="equipment-filter" type="checkbox" ${onlyAvailable?'checked':''}>My equipment only</label><label class="check-label"><input id="favorite-filter" type="checkbox" ${favoritesOnly?'checked':''}>Saved guides</label></div><div class="filters" aria-label="Muscle filters">${['All','Chest','Back','Legs','Glutes','Shoulders','Arms','Core'].map(g=>`<button class="filter ${group===g?'active':''}" data-action="filter" data-group="${g}" aria-pressed="${group===g}">${g}</button>`).join('')}</div><div id="library-results">${libraryResults()}</div><p class="legend-mini spaced">Original schematic guides explain the movement. They do not assess your personal technique. Reference links open online; illustrations and cues work offline.</p>`;}
  function chart(points,unit){
    if(points.length<2)return empty('Your trend starts here.','Log at least two entries to see a meaningful comparison.');
    const vals=points.map(p=>p.value),lo=Math.min(...vals),hi=Math.max(...vals),pad=Math.max((hi-lo)*.18,.5),min=lo-pad,max=hi+pad,x=i=>42+i*(400/(points.length-1)),y=v=>155-(v-min)/(max-min)*125;
    const line=points.map((p,i)=>`${i?'L':'M'}${x(i)} ${y(p.value)}`).join(' '),labels=[max,(max+min)/2,min];
    return `<svg class="chart" viewBox="0 0 470 190" role="img" aria-label="${esc(unit)} trend from ${shortDate(points[0].date)} to ${shortDate(points.at(-1).date)}, ${fmt(vals[0])} to ${fmt(vals.at(-1))}">${labels.map(v=>`<path d="M42 ${y(v)}h400" stroke="#edf0e9"/><text x="0" y="${y(v)+4}">${fmt(v)}</text>`).join('')}<path d="${line} L442 155H42Z" fill="#edf5e6"/><path d="${line}" stroke="#587e46" stroke-width="2.5" stroke-linejoin="round" fill="none"/>${points.map((p,i)=>`<circle cx="${x(i)}" cy="${y(p.value)}" r="3.5" fill="#285642"><title>${shortDate(p.date)}: ${fmt(p.value)} ${unit}</title></circle>`).join('')}<text x="42" y="180">${shortDate(points[0].date)}</text><text x="442" y="180" text-anchor="end">${shortDate(points.at(-1).date)}</text></svg>`;
  }
  function renderProgress(){
    const sessions=Object.values(state.sessions).sort((a,b)=>b.date.localeCompare(a.date)),finished=sessions.filter(s=>s.finishedAt),stats=sessions.reduce((a,s)=>{const t=T.totals(s);return {sets:a.sets+t.sets,volume:a.volume+t.volume};},{sets:0,volume:0}),weights=T.weeklyWeights(state).slice(-12),measurements=T.measurements(state),waists=measurements.filter(m=>T.number(m.waist)>0);
    const liftRows=T.records(state,chartExercise).reverse().map(r=>({date:r.session.date,value:Math.max(0,...r.record.sets.filter(s=>s.complete).map(s=>T.number(s.w)||0))})).filter(x=>x.value>0).slice(-12),bodyChange=weights.length>1?weights.at(-1).value-weights[0].value:null;
    return title('See how far you’ve come.','Your effort, made visible. Follow strength, consistency and body trends.',btn(`${icon('plus')}Body check-in`,'measure'))+
      `<div class="metric-grid">${metric('Workouts finished',finished.length,'since you started','calendar')}${metric('Working sets',stats.sets,'completed sets only','barbell')}${metric('Waist measurement',waists.length?`${esc(waists.at(-1).waist)}<span>cm</span>`:'—',waists.length?shortDate(waists.at(-1).date):'Add a body check-in','scale')}</div>
      <div class="two-col spaced"><section class="card"><div class="section-title"><h2>Body weight</h2><span class="badge gray">Weekly average</span></div><div class="chart-value">${weights.length?fmt(weights.at(-1).value):'—'}<small>kg</small></div><div class="chart-note"><span>${bodyChange!==null?(bodyChange>0?'+':'')+fmt(bodyChange)+' kg across this period':'Trends take more than one weigh-in'}</span></div>${chart(weights,'kg')}<p>Scale changes include water and other factors. They do not measure muscle gain or fat loss.</p></section>
      <section class="card"><div class="section-title"><h2>Strength trend</h2><span class="badge gray">Best logged load</span></div><label class="field"><select id="chart-exercise" aria-label="Exercise for strength chart">${Object.entries(E).filter(([,e])=>e.equipment.some(x=>['barbell','dumbbells','legExtension'].includes(x))).map(([id,e])=>`<option value="${id}" ${id===chartExercise?'selected':''}>${e.name}</option>`).join('')}</select></label>${chart(liftRows,'kg')}<p>Highest load in a completed set, with no estimated maximum. Compare the same exercise, setup and rep range.</p></section></div>
      <section class="card spaced"><div class="section-title"><h2>Training history</h2>${btn(`${icon('download')}Export CSV`,'csv','secondary')}</div>${sessions.length?`<div class="table-scroll"><table class="data-table"><thead><tr><th>Date</th><th>Workout</th><th>Sets</th><th>Volume</th><th>Status</th><th></th></tr></thead><tbody>${sessions.slice(0,50).map(s=>{const t=T.totals(s);return `<tr><td>${shortDate(s.date)}</td><td>${esc(s.name)}</td><td>${t.sets}</td><td>${fmt(t.volume)} kg</td><td><span class="badge ${s.finishedAt?'':'orange'}">${s.finishedAt?(s.partial?'Finished early':'Complete'):'In progress'}</span></td><td><button class="text-link" data-action="resume" data-date="${s.date}">Review ${icon('right')}</button></td></tr>`;}).join('')}</tbody></table></div>`:empty('Your first session is the starting line.','Complete a workout to build your training history.',btn('Explore my plan','plan','secondary'))}<p class="legend-mini spaced">Volume = logged external load × reps in completed sets. Paired dumbbells and per-side movements count both sides. Timed holds and bodyweight work count as sets, not kilograms.</p></section>
      <section class="card spaced"><div class="section-title"><h2>Body check-ins</h2><button class="text-link" data-action="measure">Add measurement ${icon('plus')}</button></div>${measurements.length?`<div class="table-scroll"><table class="data-table"><thead><tr><th>Date</th><th>Weight</th><th>Waist</th><th></th></tr></thead><tbody>${measurements.slice(-20).reverse().map(m=>`<tr><td>${dayLabel(m.date)}</td><td>${esc(m.bw)||'—'} ${m.bw?'kg':''}</td><td>${esc(m.waist)||'—'} ${m.waist?'cm':''}</td><td><button class="text-link" data-action="measure" data-date="${m.date}">Edit</button></td></tr>`).join('')}</tbody></table></div>`:'<p>Use similar conditions each time. A weekly waist measurement can add context to your weight trend.</p>'}</section>`;
  }
  function coachInsights(){
    const recent=Object.values(state.sessions).filter(s=>s.date>=T.addDays(T.today(),-14)),issues=[];
    const pain=recent.flatMap(s=>Object.entries(s.exercises).filter(([,r])=>r.pain||r.skipReason==='Pain').map(([id])=>({date:s.date,name:E[id]?.name||id})));
    if(pain.length)issues.push({icon:'heart',title:'Give discomfort your attention',text:`Pain was logged for ${pain.map(x=>x.name).filter((x,i,a)=>a.indexOf(x)===i).join(', ')}. Pause painful movements and get qualified guidance if it persists.`});
    const completed=recent.filter(s=>s.finishedAt).length;
    issues.push({icon:'calendar',title:completed?`${completed} workouts in the last 14 days`:'Build a repeatable rhythm',text:completed?'Keep your planned days realistic. Consistent sessions and recovery help you see what is working.':`Your ${state.config.days.length}-day plan is ready. Start comfortably, then use the same movements to learn what progress feels like.`});
    const ids=[...new Set(T.routines(state.config).flatMap(p=>p.ex.map(e=>e.id)))];
    ids.forEach(id=>{const entry=T.routines(state.config).flatMap(p=>p.ex).find(e=>e.id===id),r=T.recommend(state,entry,T.addDays(T.today(),1));if(r.kind!=='start')issues.push({icon:r.kind==='up'?'chart':'info',title:E[id].name,text:r.text,date:r.date});});
    if(issues.length<3)issues.push({icon:'spark',title:'Effort adds context to the numbers',text:'Log “reps left” after a set: how many more clean reps you could have done. Two or three is a useful starting margin. Leave it blank if unsure.'});
    return issues;
  }
  function renderCoach(){
    const start=T.monday(T.today()),ss=weekSessions(start),done=ss.filter(s=>s.finishedAt).length,sets=ss.reduce((n,s)=>n+T.totals(s).sets,0),plannedDue=Array.from({length:7},(_,i)=>T.addDays(start,i)).filter(d=>d<T.today()&&T.planAt(state.config,d)),missed=plannedDue.filter(d=>!T.sessionOn(state,d)?.finishedAt);
    return title('A little direction. A lot of progress.','Understand your next step, and keep a useful record for a coach.')+
      `<div class="filters"><button class="filter ${coachMode==='guidance'?'active':''}" data-action="coach-mode" data-mode="guidance" aria-pressed="${coachMode==='guidance'}">My guidance</button><button class="filter ${coachMode==='review'?'active':''}" data-action="coach-mode" data-mode="review" aria-pressed="${coachMode==='review'}">Coach review</button></div>
      <div class="coach-grid"><div class="stack"><section class="card soft"><span class="eyebrow">${coachMode==='review'?'WEEKLY REVIEW':'YOUR NEXT STEP'}</span><div class="coach-summary">${done?'You’re putting in the work.<br>Let’s make it count.':'Your starting point is<br>something to build on.'}</div><p>${coachMode==='review'?`Week of ${shortDate(start)}. ${missed.length} past scheduled session${missed.length===1?'':'s'} not completed. Today and future sessions are not counted as missed.`:'Follow the plan, track how your sets feel, and keep your movements controlled. Adjustments below come from simple rules applied to your log.'}</p><div class="stat-inline"><div><b>${done}<small> / ${state.config.days.length}</small></b><small>sessions this week</small></div><div><b>${sets}</b><small>working sets</small></div><div><b>${goalName()==='General fitness'?'Fitness':'Strength'}</b><small>your focus</small></div></div></section>
      <section class="card"><div class="section-title"><h2>${coachMode==='review'?'Training observations':'What your log is telling us'}</h2><span class="badge gray">On-device guidance</span></div>${coachInsights().map(i=>`<div class="insight"><span class="insight-icon">${icon(i.icon)}</span><div><h3>${esc(i.title)}</h3><p>${esc(i.text)}</p>${i.date?`<span class="badge gray">Based on ${shortDate(i.date)}</span>`:''}</div></div>`).join('')}</section></div>
      <div class="stack"><section class="card"><h2>${coachMode==='review'?'Coach’s review notes':'Your training focus'}</h2><p class="spaced">A space for your own reflections or notes from a coach. Notes stay on this device until you choose to export them.</p><label class="field spaced">This week’s focus<textarea id="coach-notes" rows="5" maxlength="3000" placeholder="What went well? What needs more practice? What will I focus on next?">${esc(state.config.coachNotes||'')}</textarea></label>${btn(`${icon('download')}Download coach report`,'report','secondary full spaced')}</section>
      <section class="card coach-card"><div class="coach-top"><div class="coach-symbol">${icon('shield')}</div><h3>Train confidently on your own</h3></div><p>Open the guide before unfamiliar movements. Warm up, set up your equipment carefully, and finish with clean reps remaining.</p><p class="spaced">Your bench has stands, but rated safety catches have not been confirmed. Solo barbell bench press stays out of the plan until you enable those in Settings.</p><a href="#exercises" class="text-link">Explore movement guides ${icon('arrow')}</a></section>
      <section class="card"><h3>How the coach works</h3><p class="spaced">This is a training companion using clear progression rules. It does not watch your form or connect you to a live coach. The downloadable report helps a trainer review your actual sets, effort and notes.</p></section></div></div>`;
  }
  function renderSettings(){
    const c=state.config,option=(value,label,current)=>`<option value="${value}" ${value===current?'selected':''}>${label}</option>`,field=(key,label,help)=>`<label class="field">${label}<input type="text" inputmode="decimal" name="${key}" value="${esc(c[key]??'')}" placeholder="Not set"><small>${help}</small></label>`;
    return title('Make this space yours.','Your goals, your schedule, your equipment. You can adjust them as you grow.')+
      `<div class="settings-grid"><form id="settings-form" class="stack"><section class="card"><h3>Your training profile</h3><div class="form-grid"><label class="field">What should we call you?<input name="name" value="${esc(c.name)}" maxlength="40" autocomplete="given-name" placeholder="Your first name"></label><label class="field">Main goal<select name="goal">${option('fitness','General fitness',c.goal)}${option('muscle','Muscle & strength',c.goal)}${option('fatloss','Fat loss & strength',c.goal)}</select></label><label class="field">Training experience<select name="experience">${option('new','New or returning · 2 sets',c.experience)}${option('experienced','Training consistently · 3 sets',c.experience)}</select></label><label class="field">Time per session<select name="duration">${[30,45,60].map(x=>option(x,`${x} minutes`,c.duration)).join('')}</select></label><label class="field wide">Plan starts<input name="start" type="date" value="${c.start}" required></label><div class="field wide">Training days · choose 2 to 4<div class="day-checks">${[1,2,3,4,5,6,0].map(n=>`<label><input type="checkbox" name="days" value="${n}" ${c.days.includes(n)?'checked':''}><span>${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][n]}</span></label>`).join('')}</div><small>Four days uses an upper/lower split. Two or three days uses full-body sessions.</small></div></div></section>
      <section class="card"><h3>Your home gym</h3><div class="checkbox-grid">${Object.entries(EQUIPMENT).map(([k,label])=>`<label class="check-label"><input type="checkbox" name="gear-${k}" ${c.equipment[k]?'checked':''}><span>${label}</span></label>`).join('')}</div><div class="notice spaced">Enable “Rated bench safety arms” only if you have properly rated catches, positioned and tested for your range of motion. The Rebel Active stands are not confirmed as safety catches.</div><div class="form-grid spaced">${field('barWeight','Empty bar (kg)','8.7 kg per the Domyos listing.')}${field('maxLoad','Total barbell limit (kg)','88.7 kg = bar + 80 kg of plates; sleeve fit may reduce this.')}${field('increment','Smallest balanced increase (kg)','2 kg = one 1 kg plate added to each end.')}${field('attachmentMax','Leg attachment limit (kg)','25 kg per the Rebel Active listing.')}${field('dumbbellMax','Per-dumbbell limit (kg)','42 kg is the inventory ceiling for a matched pair. Check sleeve space.')}${field('verticalMax','Vertical-grip dumbbell limit (kg)','15 kg maximum per the Domyos collar guidance.')}</div><p class="spaced">Your kit has two 2 kg dumbbell handles and plates: 4 × 10 kg, 4 × 5 kg, 8 × 2 kg, 4 × 1 kg. Secure plates with the supplied collars; this kit’s dumbbells are not for overhead exercises.</p><div class="button-row spaced">${btn(`${icon('barbell')}Plate calculator`,'plates','secondary')}<a class="text-link" href="https://www.decathlon.mt/p/10804-188923-weight-training-93-kg-partly-recycled-cast-iron-dumbbells-and-bar-set.html" target="_blank" rel="noopener noreferrer">Domyos specifications ↗</a><a class="text-link" href="https://kvhmalta.com/product/rebel-active-multifunctional-adjustable-training-bench-with-preacher-bench/" target="_blank" rel="noopener noreferrer">Bench specifications ↗</a></div></section>
      <section class="card"><h3>During your workout</h3><label class="check-label"><input type="checkbox" name="autoRest" ${c.autoRest?'checked':''}><span>Start the rest timer when I complete a set<small>The clock begins after you tap the checkmark, so typing a number never starts it.</small></span></label></section><div id="settings-error" class="form-error" role="alert"></div><button class="btn" type="submit">Save my preferences ${icon('check')}</button></form>
      <div class="stack"><section class="card soft"><span class="eyebrow">BUILT AROUND YOU</span><h2 class="spaced">Four sessions.<br>Your own home gym.</h2><p class="spaced">Your starting profile is based on the equipment you shared and your general-fitness goal. Adjust the limits if your actual kit or its instructions differ.</p><p class="spaced">The complete set’s advertised weight includes all three bars. That is different from how much can be loaded on one barbell.</p></section>
      <section class="card"><h3>Keep your progress safe</h3><p class="spaced">Your logs live in this browser. They do not sync between devices. Download a backup before clearing browser data or changing phones.</p><p class="spaced">${c.lastBackup?'Last backup requested: '+dayLabel(c.lastBackup):'No backup downloaded yet.'}</p><div class="backup-buttons spaced">${btn(`${icon('download')}Backup JSON`,'backup','secondary')}${btn('Import backup','import','secondary')}${btn('Copy backup text','copy-backup','secondary')}${btn('Export sets CSV','csv','secondary')}</div><input id="import-file" type="file" accept=".json,application/json" hidden><p class="spaced">Imports merge newer workouts and measurements. Your current profile stays in place.</p>${readFailure?btn('Download unreadable original','raw-backup','secondary full spaced'):''}</section>
      <section class="card"><h3>Take your plan with you</h3><p class="spaced">Download the next four weeks as all-day calendar events, then set your preferred times in your calendar.</p>${btn(`${icon('calendar')}Download calendar`,'calendar','secondary full spaced')}</section><section class="card"><h3>Try the full experience</h3><p class="spaced">Explore charts and coaching with clearly labelled sample logs in a separate demo space.</p><a class="text-link" href="?demo=1#today">Open demo ${icon('arrow')}</a><a class="text-link" href="programme.html" target="_blank" rel="noopener">Training principles ↗</a></section></div></div>`;
  }
  function currentSession(){return state.sessions[activeDate];}
  function renderWorkout(){
    const s=currentSession();if(!s)return title('Workout not found.','Open your weekly plan to choose a session.')+btn('Open my plan','plan');
    const t=T.totals(s),total=s.snapshot.reduce((n,e)=>n+(s.exercises[e.id]?.sets.length||0),0),review=!!s.finishedAt;
    return title(esc(s.name),`${dayLabel(s.date)} · ${review?(s.partial?'Finished early · partial session':'Completed session'):'Your session is saved as you go'}`,btn(`${icon('left')}Overview`,'today','secondary'))+
      `${s.readiness==='low'?'<div class="notice spaced" style="margin-bottom:20px">You reported low energy. Keep the session comfortable, use a lighter load if needed, and skip a movement if you cannot maintain good form.</div>':''}`+
      `<div class="workout-layout"><div class="stack">${s.snapshot.map((e,index)=>workoutExercise(e,index,s,review)).join('')}<section class="card"><h3>Session notes</h3><label class="field spaced"><span class="muted">Energy, technique, wins, or anything you want to remember</span><textarea id="session-notes" rows="3" maxlength="3000" ${review?'readonly':''} placeholder="How did today feel?">${esc(s.notes)}</textarea></label></section></div><aside class="card session-aside"><span class="eyebrow">${review?'SESSION SUMMARY':'YOUR SESSION'}</span><h2 class="spaced">${review?'Good work. Logged.':'One set at a time.'}</h2><div class="workout-progress"><i id="session-progress" style="width:${total?Math.round(t.sets/total*100):0}%"></i></div><p id="session-count">${t.sets} of ${total} sets completed</p><div class="session-stat"><span>Volume lifted</span><b id="session-volume">${fmt(t.volume)} kg</b></div><div class="session-stat"><span>Readiness</span><b>${s.readiness==='pain'?'Pain reported':s.readiness==='low'?'Low energy':'Ready'}</b></div><div class="notice green spaced">“Reps left” means how many more clean reps you could do. Aim to finish with 2–3 in reserve. Leave it blank if unsure.</div>${review?btn('Reopen to edit','reopen','secondary full spaced'):btn(`${icon('check')}Finish workout`,'finish','full spaced')}<button class="text-link" data-action="plates">${icon('barbell')}Plate calculator</button><p class="legend-mini">${review?'Your completed sets are included in Progress.':'You can leave and resume this workout at any time.'}</p></aside></div>`;
  }
  function workoutExercise(e,index,s,review){
    const r=s.exercises[e.id],ex=E[e.id],weighted=ex?ex.equipment.some(k=>['barbell','dumbbells','legExtension'].includes(k)):r.sets.some(x=>x.w!==''),last=T.records(state,e.id,s.date).find(x=>x.record.sets.some(y=>y.complete)),pg=T.recommend(state,e,s.date),weightLabel=ex?.equipment.includes('dumbbells')?'kg / dumbbell':'kg total';
    return `<section class="card exercise-card ${r.skipped?'skipped':''}" id="exercise-${esc(e.id)}"><div class="exercise-card-head"><span class="exercise-number">${String(index+1).padStart(2,'0')}</span><div><h3>${esc(e.name)}</h3><p>${prescription({...e,target:r.sets.length})} · ${e.rest}s rest</p></div>${!review?`<div class="exercise-actions"><button class="icon-button" data-action="swap" data-id="${esc(e.id)}" aria-label="Swap ${esc(e.name)}">${icon('swap')}</button></div>`:''}</div>${ex?`<button class="guide-link" data-action="guide" data-id="${e.id}">${icon('play')}<span>Learn the movement</span><span>Setup · Full rep · Form ${icon('right')}</span></button>`:''}<div class="set-area">${ex&&!T.available(e.id,state.config)?'<div class="notice spaced">This saved exercise needs equipment that is not enabled in your profile. Review the guide and choose an appropriate alternative.</div>':''}${r.skipped?`<p>Skipped · ${esc(r.skipReason||'Other')}</p>${!review?`<button class="text-link" data-action="unskip" data-id="${esc(e.id)}">Bring this exercise back</button>`:''}`:
      `${!review?`<div class="progression-tip">${icon('spark')}<span>${esc(pg.text)}${pg.kind==='up'&&s.readiness!=='low'?` <button class="text-link" data-action="apply-load" data-id="${esc(e.id)}" data-weight="${pg.next}">Use ${fmt(pg.next)} kg</button>`:''}</span></div>`:''}<div class="set-help">${weighted?(ex?.equipment.includes('dumbbells')?'Log the weight of one dumbbell, including its handle.':ex?.equipment.includes('legExtension')?'Log plates loaded on this attachment; compare only this setup.':'Log the total load, including the bar.'):'No external weight needed.'} ${ex?.side?'Enter reps completed on each side.':''}</div><table class="set-table"><thead><tr><th scope="col">Set</th><th scope="col">Previous</th>${weighted?`<th scope="col">${weightLabel}</th>`:''}<th scope="col">${e.unit==='seconds'?'Seconds':e.unit==='metres'?'Metres':'Reps'}</th>${e.unit==='reps'?'<th scope="col">Reps left</th>':''}<th scope="col"><span class="small">✓</span></th></tr></thead><tbody>${r.sets.map((x,i)=>{const prev=last?.record.sets[i];return `<tr class="${x.complete?'logged':''}"><td>${i+1}</td><td class="previous">${prev?.complete?`${prev.w?esc(prev.w)+' × ':''}${esc(prev.r)}${e.unit==='seconds'?'s':''}`:'—'}</td>${weighted?`<td><input inputmode="decimal" data-set="w" data-id="${esc(e.id)}" data-index="${i}" aria-label="${esc(e.name)} set ${i+1} weight" value="${esc(x.w)}" placeholder="${prev?.w?esc(prev.w):'kg'}" ${review||x.complete?'disabled':''}></td>`:''}<td><input inputmode="numeric" data-set="r" data-id="${esc(e.id)}" data-index="${i}" aria-label="${esc(e.name)} set ${i+1} ${e.unit}" value="${esc(x.r)}" placeholder="${e.range.join('–')}" ${review||x.complete?'disabled':''}></td>${e.unit==='reps'?`<td><input inputmode="numeric" data-set="rir" data-id="${esc(e.id)}" data-index="${i}" aria-label="${esc(e.name)} set ${i+1} reps left" value="${esc(x.rir)}" placeholder="0–5" ${review||x.complete?'disabled':''}></td>`:''}<td><button class="set-check ${x.complete?'checked':''}" data-action="check-set" data-id="${esc(e.id)}" data-index="${i}" aria-label="${x.complete?'Edit':'Complete'} ${esc(e.name)} set ${i+1}" aria-pressed="${x.complete}" ${review?'disabled':''}>${icon('check')}</button></td></tr>`;}).join('')}</tbody></table><div class="form-error" id="error-${esc(e.id)}" role="alert"></div>${!review?`<div class="set-bottom"><button data-action="add-set" data-id="${esc(e.id)}">+ Add set</button><button data-action="rest" data-id="${esc(e.id)}">${icon('clock')} Rest ${e.rest}s</button><button data-action="skip" data-id="${esc(e.id)}">Skip exercise</button></div>`:''}`}</div></section>`;
  }
  function modal(titleText,eyebrow,body){
    stopAnimation();if(!$('#dialog').open)modalOpener=document.activeElement;
    $('#dialog-content').innerHTML=`<div class="modal-head"><div><span class="eyebrow">${eyebrow}</span><h2 id="dialog-title">${titleText}</h2></div><button class="icon-button" data-action="close" aria-label="Close dialog">${icon('close')}</button></div><div class="modal-body">${body}</div>`;
    if(!$('#dialog').open)$('#dialog').showModal();$('#dialog').scrollTop=0;
  }
  function closeModal(){stopAnimation();$('#dialog').close();}
  function stopAnimation(){if(animation)clearInterval(animation);animation=null;}
  function guide(id){
    const e=E[id];if(!e){toast('A detailed guide is not available for this older exercise.');return;}
    const saved=(state.config.favorites||[]).includes(id);
    modal(esc(e.name),`${e.group} · ${equipmentText(id)}`,`<div class="guide-stage"><div class="pose-pair" id="pose-pair"><figure>${figure(id,0)}<figcaption>01 · Starting position</figcaption></figure><figure>${figure(id,1)}<figcaption>02 · ${e.unit==='seconds'?'Hold steady':'End of movement'}</figcaption></figure></div><div class="motion-panel" id="motion-panel" hidden></div><div class="motion-controls"><button class="btn secondary" data-action="animate" data-id="${id}">${icon('play')}Play full rep</button><small>Schematic side view · Illustrations are simplified. Read the cues below.</small></div></div>
      ${!T.available(id,state.config)?'<div class="notice spaced">This movement needs equipment that is not enabled in your profile.</div>':''}
      <ol class="steps">${e.steps.map((step,i)=>`<li><span>${i+1}</span><div><strong>${['Set up your position','Make the movement','Return with control'][i]}</strong><p>${esc(step)}</p></div></li>`).join('')}</ol>
      <div class="notice"><strong>Common form mistakes</strong><br>${esc(e.mistakes)}</div>${e.solo?`<div class="notice green spaced"><strong>When training alone</strong><br>${esc(e.solo)}</div>`:''}${id==='goblet'?'<div class="notice spaced">Your Domyos kit specifies a 15 kg maximum in vertical grip. Secure its collars and follow the product instructions.</div>':''}
      <div class="guide-bottom"><a class="text-link" href="${e.source}" target="_blank" rel="noopener noreferrer">${e.sourceLabel} ↗</a><button class="text-link" data-action="favorite" data-id="${id}">${icon('star')}${saved?'Saved guide':'Save this guide'}</button></div>`);
  }
  function animate(id,button){
    if(animation){stopAnimation();button.innerHTML=icon('play')+'Play full rep';$('#pose-pair').hidden=false;$('#motion-panel').hidden=true;return;}
    $('#pose-pair').hidden=true;$('#motion-panel').hidden=false;button.innerHTML=icon('pause')+'Pause demo';
    const started=performance.now();
    const draw=()=>{const elapsed=(performance.now()-started)%6000,phase=elapsed<2500?elapsed/2500:elapsed<3000?1:elapsed<5500?1-(elapsed-3000)/2500:0;$('#motion-panel').innerHTML=figure(id,phase)+`<small class="muted">${E[id].unit==='seconds'?'Hold steady and breathe':elapsed<2500?'Move with control':elapsed<3000?'Pause briefly':elapsed<5500?'Return to your start':'Reset and repeat'}</small>`;};
    draw();animation=setInterval(draw,60);
  }
  function planPreview(d,key){
    const p=key?T.routines(state.config).find(x=>x.key===key):T.planAt(state.config,d);
    if(!p){modal('Room to recover.','RECOVERY DAY',`<p class="muted">${dayLabel(d)} is a recovery day. Take an easy walk, enjoy some gentle mobility, or simply rest.</p><div class="button-row spaced">${btn('View weekly plan','plan')}${btn('Body check-in','measure','secondary')}</div>`);return;}
    modal(esc(p.name),dayLabel(d),`<p class="muted">${esc(p.tag)} · Around ${state.config.duration} minutes</p><div class="spaced">${p.ex.map(exerciseLine).join('')}</div><div class="notice green spaced">Start light and use the guides to learn each movement. Finish each set with 2–3 clean reps left.</div>${btn(`${icon('play')}Start this workout today`,'start','full spaced',`data-key="${p.key}"`)}`);
  }
  function startWorkout(key){
    if(readFailure){toast('Restore a readable backup before starting a workout. Your original data is protected.');return;}
    const existing=state.sessions[T.today()];
    if(existing){closeModal();nav('workout/'+existing.date);toast(existing.finishedAt?'Today’s completed workout is already logged.':'Resuming today’s workout.');return;}
    pendingPlan=T.routines(state.config).find(p=>p.key===key)||T.nextPlan(state)||T.routines(state.config)[0];
    if(!pendingPlan)return;
    for(let i=0;i<14;i++){const d=T.addDays(T.today(),i),p=T.planAt(state.config,d);if(p?.key===pendingPlan.key&&!T.sessionOn(state,d)){pendingPlan={...pendingPlan,scheduledFor:d};break;}}
    modal('How are you feeling?','BEFORE '+esc(pendingPlan.name.toUpperCase()),`<form id="readiness-form"><p class="muted">A quick check-in helps you make a sensible choice for today.</p><div class="choice-grid spaced"><label class="choice"><input type="radio" name="readiness" value="normal" checked><span>Ready to go<small>Normal energy</small></span></label><label class="choice"><input type="radio" name="readiness" value="low"><span>A little tired<small>Keep it comfortable</small></span></label><label class="choice"><input type="radio" name="readiness" value="pain"><span>Feeling pain<small>Pause and reassess</small></span></label></div><section class="card soft spaced"><h3>Ease into the session</h3><ol class="warmup-list"><li>Start with 5–10 minutes of easy movement.</li><li>Check bench locks, collars, floor space and equipment limits.</li><li>Rehearse unfamiliar movements, then do lighter warm-up sets before working sets.</li></ol><label class="check-label"><input name="ready" type="checkbox" required><span>I’ve warmed up and checked my setup.</span></label></section><p id="readiness-error" class="form-error" role="alert"></p><button class="btn full" type="submit">Let’s begin ${icon('arrow')}</button></form>`);
  }
  function finishWorkout(){
    const s=currentSession(),stats=T.totals(s);if(stats.sets===0){toast('Complete at least one set before finishing. You can leave and return later.');return;}
    const complete=T.completeSession(s),remaining=s.snapshot.reduce((n,e)=>n+(s.exercises[e.id].skipped?0:s.exercises[e.id].sets.filter(x=>!x.complete).length),0);
    modal('Make a note of today.','FINISH YOUR WORKOUT',`<form id="finish-form"><p class="muted">${stats.sets} working sets · ${fmt(stats.volume)} kg volume</p>${!complete?`<div class="notice spaced">${remaining} planned sets are still uncompleted. Finishing now records a partial session; uncompleted sets do not count toward your progress.</div>`:''}<label class="field spaced">How did the session feel?<select name="effort"><option value="manageable">Manageable</option><option value="challenging">Challenging, with good control</option><option value="too-hard">Too hard today</option></select></label><label class="check-label spaced"><input name="pain" type="checkbox"><span>I felt pain or unusual discomfort<small>This will be highlighted in your coach review.</small></span></label><label class="field spaced">Anything to remember?<textarea name="notes" rows="3" maxlength="3000" placeholder="A small win or something to adjust…">${esc(s.notes)}</textarea></label><div class="button-row spaced"><button class="btn" type="submit">${icon('check')}${complete?'Save completed workout':'Save partial workout'}</button>${btn('Keep training','close','secondary')}</div></form>`);
  }
  function measure(d=T.today()){
    if(!T.validDate(d))d=T.today();const m=state.metrics[d.slice(0,7)]?.days[String(T.date(d).getDate())]||{};
    modal('A small check-in. A clearer picture.','BODY MEASUREMENTS',`<form id="measure-form"><div class="form-grid"><label class="field wide">Date<input id="measure-date" type="date" name="date" value="${d}" max="${T.today()}" required></label><label class="field">Body weight (kg)<input name="bw" inputmode="decimal" value="${esc(m.bw||'')}" placeholder="e.g. 80.5"></label><label class="field">Waist (cm)<input name="waist" inputmode="decimal" value="${esc(m.waist||'')}" placeholder="e.g. 86"></label></div><p class="muted small spaced">Use similar conditions each time. Your weekly average matters more than a single reading. These measurements cannot distinguish fat from muscle.</p><p class="form-error" id="measure-error" role="alert"></p><button class="btn full" type="submit">Save check-in ${icon('check')}</button></form>`);
  }
  function plates(){modal('Load your bar with confidence.','DOMYOS PLATE CALCULATOR',`<form id="plate-form"><div class="form-grid"><label class="field">What are you loading?<select name="kind"><option value="barbell">Barbell · total weight</option><option value="pair">Matched dumbbells · each</option></select></label><label class="field">Target weight (kg)<input name="total" inputmode="decimal" value="28.7" required></label></div><p class="muted small spaced">Includes the empty bar or handle. Uses your kit’s 4 × 10, 4 × 5, 8 × 2 and 4 × 1 kg plates, shared across both dumbbells when making a pair.</p><button class="btn spaced" type="submit">Calculate plates ${icon('arrow')}</button><div id="plate-result" class="spaced" aria-live="polite"></div><p class="legend-mini spaced">Inventory calculation only. Check sleeve space, collar security, manufacturer limits, and your bench’s rating before lifting. Plates already loaded elsewhere are assumed available.</p></form>`);}
  function exportPayload(){return {app:'iron-logbook',schema:4,appVersion:'2.0.0',exported:new Date().toISOString(),...state};}
  function download(text,name,type='application/json'){
    const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);
  }
  function backup(){download(JSON.stringify(exportPayload(),null,2),`iron-logbook-${T.today()}.json`);state.config.lastBackup=T.today();save();toast('Backup download requested. Keep the file somewhere safe.');}
  function csv(){const rows=[['date','workout','exercise','set','weight_kg','amount','unit','reps_left','completed','skipped']];Object.values(state.sessions).sort((a,b)=>a.date.localeCompare(b.date)).forEach(s=>s.snapshot.forEach(e=>s.exercises[e.id].sets.forEach((x,i)=>rows.push([s.date,s.name,e.name,i+1,x.w,x.r,e.unit,x.rir,x.complete,s.exercises[e.id].skipped]))));const cell=x=>'"'+String(x??'').replace(/^[=+\-@\t\r]/,"'$&").replace(/"/g,'""')+'"';download(rows.map(r=>r.map(cell).join(',')).join('\r\n'),`iron-logbook-sets-${T.today()}.csv`,'text/csv;charset=utf-8');toast('CSV download requested.');}
  function report(){const lines=['IRON LOGBOOK · COACH REVIEW',`Prepared ${T.today()}`,`Goal: ${goalName()}`,`Schedule: ${state.config.days.length} days/week`, '','OBSERVATIONS',...coachInsights().map(x=>`${x.title}: ${x.text}`),'','REVIEW NOTES',state.config.coachNotes||'No notes yet.','','LAST 14 DAYS'];Object.values(state.sessions).filter(s=>s.date>=T.addDays(T.today(),-14)).sort((a,b)=>a.date.localeCompare(b.date)).forEach(s=>{lines.push(`\n${s.date} · ${s.name} · ${s.finishedAt?'Finished':'In progress'} · Readiness: ${s.readiness||'not recorded'}`);s.snapshot.forEach(e=>{const r=s.exercises[e.id];lines.push(`${e.name}: ${r.skipped?'SKIPPED ('+r.skipReason+')':r.sets.map((x,i)=>`set ${i+1}: ${x.w?x.w+' kg × ':''}${x.r||'—'} ${e.unit}, ${x.rir||'unknown'} reps left, ${x.complete?'completed':'uncompleted'}`).join('; ')}`);});lines.push('Notes: '+(s.notes||'None'));});lines.push('','BODY CHECK-INS',...T.measurements(state).slice(-14).map(m=>`${m.date}: ${m.bw||'—'} kg, waist ${m.waist||'—'} cm`));download(lines.join('\n'),`iron-logbook-coach-${T.today()}.txt`,'text/plain');toast('Coach report downloaded. Nothing was sent to anyone.');}
  function calendar(){const stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z'),lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Iron Logbook//Home Gym//EN','CALSCALE:GREGORIAN'];for(let i=0;i<28;i++){const d=T.addDays(T.today(),i),p=T.planAt(state.config,d);if(!p)continue;lines.push('BEGIN:VEVENT',`UID:iron-${d}-${p.key}@local`,`DTSTAMP:${stamp}`,`DTSTART;VALUE=DATE:${d.replace(/-/g,'')}`,`DTEND;VALUE=DATE:${T.addDays(d,1).replace(/-/g,'')}`,`SUMMARY:Iron Logbook - ${p.name}`,'DESCRIPTION:Open Iron Logbook for your equipment-aware training plan.','END:VEVENT');}lines.push('END:VCALENDAR');download(lines.join('\r\n'),`iron-logbook-plan-${T.today()}.ics`,'text/calendar');toast('Four-week calendar downloaded. Add your preferred times after import.');}
  async function importFile(file){
    if(!file)return;if(file.size>10*1024*1024){toast('Choose a backup smaller than 10 MB.');return;}
    try {const payload=JSON.parse(await file.text()),merged=T.mergeBackup(state,payload);modal('Bring your progress together.','IMPORT BACKUP',`<p class="muted">This backup contains ${Object.keys(payload.sessions||{}).length} workouts. Newer workouts and measurements will be merged; your current profile will stay in place.</p><div class="notice spaced">${readFailure?'Your current stored file is unreadable. Download the original in Settings before replacing it with this restored log.':'Keep a backup of this device’s log before importing changes.'}</div><div class="button-row spaced">${btn('Import and merge','confirm-import')}${btn('Cancel','close','secondary')}</div>`);$('#dialog-content [data-action="confirm-import"]').onclick=()=>{if(readFailure){try{download(localStorage.getItem(storageKey)||'',`iron-logbook-original-${T.today()}.txt`,'text/plain');}catch{}}state=merged;readFailure=false;const ok=save();closeModal();render();toast(ok?'Backup merged successfully.':'Imported in memory. Download a backup: browser storage is still unavailable.');};}
    catch(error){toast(error.message||'This backup could not be imported.');}
  }
  function wake(){if(document.hidden||!navigator.wakeLock||wakeLock)return;navigator.wakeLock.request('screen').then(lock=>{wakeLock=lock;lock.addEventListener('release',()=>wakeLock=null);}).catch(()=>{});}
  function startRest(seconds,label){
    stopRest();timer={end:Date.now()+seconds*1000,total:seconds,label};state.config.activeTimer=timer;save();
    try{const Audio=window.AudioContext||window.webkitAudioContext;if(Audio){audioContext??=new Audio();audioContext.resume();}}catch{}
    wake();tick();
  }
  function stopRest(){timer=null;delete state.config.activeTimer;$('#rest-timer').hidden=true;document.body.classList.remove('timer-visible');if(wakeLock)wakeLock.release().catch(()=>{});wakeLock=null;save();}
  function tick(){if(!timer)return;const remaining=Math.max(0,Math.ceil((timer.end-Date.now())/1000));$('#rest-timer').hidden=false;document.body.classList.add('timer-visible');$('#rest-label').textContent=remaining?'REST · '+timer.label:'REST COMPLETE';$('#rest-time').textContent=Math.floor(remaining/60)+':'+String(remaining%60).padStart(2,'0');$('#rest-progress').style.width=Math.min(100,remaining/timer.total*100)+'%';
    if(!remaining&&!timer.fired){timer.fired=true;toast('Rest complete. Begin the next set when you feel ready.');try{navigator.vibrate?.([120,80,120]);if(audioContext){const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.connect(gain);gain.connect(audioContext.destination);gain.gain.value=.1;osc.frequency.value=660;osc.start();osc.stop(audioContext.currentTime+.25);}}catch{}if(wakeLock)wakeLock.release().catch(()=>{});wakeLock=null;}
  }
  function updateSessionStats(){const s=currentSession();if(!s)return;const t=T.totals(s),total=s.snapshot.reduce((n,e)=>n+s.exercises[e.id].sets.length,0);$('#session-count').textContent=`${t.sets} of ${total} sets completed`;$('#session-volume').textContent=fmt(t.volume)+' kg';$('#session-progress').style.width=(total?t.sets/total*100:0)+'%';}
  function replaceExercise(id){const s=currentSession(),idx=s.snapshot.findIndex(e=>e.id===id),target=$('#exercise-'+id);if(target)target.outerHTML=workoutExercise(s.snapshot[idx],idx,s,!!s.finishedAt);updateSessionStats();}
  function swap(id){
    const s=currentSession(),r=s.exercises[id];if(r.sets.some(x=>x.w!==''||x.r!==''||x.complete)){toast('This exercise already has data. Keep it in your log; you can skip its remaining work.');return;}
    const candidates=Object.keys(E).filter(k=>k!==id&&E[k].group===E[id]?.group&&T.available(k,state.config)&&!s.snapshot.some(e=>e.id===k));
    modal('Find a movement that fits.','SWAP EXERCISE',candidates.length?`<p class="muted">Available alternatives for ${esc(E[id]?.group.toLowerCase()||'this movement')} using your equipment.</p><div class="spaced">${candidates.map(k=>`<button class="btn secondary full spaced" data-action="choose-swap" data-from="${esc(id)}" data-id="${k}">${E[k].name}${icon('arrow')}</button>`).join('')}</div>`:empty('No matching alternatives.','There is no other movement for this muscle group with your current equipment. You can skip the exercise and leave a note.'));
  }
  function render(){
    const hash=decodeURIComponent(location.hash.slice(1)||'today');if(hash==='main')return;
    const [page,d]=hash.split('/');route=['today','plan','exercises','progress','coach','settings','workout'].includes(page)?page:'today';activeDate=route==='workout'&&T.validDate(d)?d:null;
    const routes=[['today','Overview','home'],['plan','My plan','calendar'],['exercises','Exercises','book'],['progress','Progress','chart'],['coach','My coach','spark']];
    const selected=route==='workout'?'today':route;
    $('#desktop-nav').innerHTML=routes.map(([r,label,i])=>`<a href="#${r}" class="nav-item ${selected===r?'active':''}" ${selected===r?'aria-current="page"':''}>${icon(i)}${label}</a>`).join('');
    $('#mobile-nav').innerHTML=routes.map(([r,label,i])=>`<a href="#${r}" class="${selected===r?'active':''}" ${selected===r?'aria-current="page"':''}>${icon(i)}${r==='today'?'Today':label}</a>`).join('');
    $('#page-name').textContent=routes.find(x=>x[0]===route)?.[1]||(route==='workout'?'Your workout':'Settings');$('#settings-nav').innerHTML=icon('settings')+'Settings';$('#settings-nav').classList.toggle('active',route==='settings');$('#settings-button').innerHTML=icon('settings');$('#avatar').textContent=(state.config.name||'You').slice(0,1).toUpperCase();$('#rest-icon').innerHTML=icon('clock');$('#save-status').textContent=storageBlocked?'Not saved':demo?'Demo data':'Saved on this device';
    const renders={today:renderToday,plan:renderPlan,exercises:renderLibrary,progress:renderProgress,coach:renderCoach,settings:renderSettings,workout:renderWorkout};$('#main').innerHTML=renders[route]();document.title=`${route==='workout'?'Workout':$('#page-name').textContent} · Iron Logbook`;
  }
  document.addEventListener('click',event=>{
    const b=event.target.closest('[data-action],[data-route]');if(!b||b.disabled)return;
    if(b.dataset.route){closeModal();nav(b.dataset.route);return;}
    const a=b.dataset.action,id=b.dataset.id,s=currentSession();
    if(['today','plan','settings'].includes(a)){closeModal();nav(a);}
    else if(a==='close')closeModal();
    else if(a==='guide')guide(id);
    else if(a==='animate')animate(id,b);
    else if(a==='favorite'){const list=new Set(state.config.favorites||[]);list.has(id)?list.delete(id):list.add(id);state.config.favorites=[...list];save();guide(id);}
    else if(a==='filter'){group=b.dataset.group;render();}
    else if(a==='coach-mode'){coachMode=b.dataset.mode;render();}
    else if(a==='week-prev'||a==='week-next'){week=T.addDays(week,a==='week-prev'?-7:7);render();}
    else if(a==='week-now'){week=T.monday(T.today());render();}
    else if(a==='day'){const d=b.dataset.date;if(T.sessionOn(state,d))nav('workout/'+T.sessionOn(state,d).date);else planPreview(d);}
    else if(a==='resume'){closeModal();nav('workout/'+b.dataset.date);}
    else if(a==='start')startWorkout(b.dataset.key);
    else if(a==='measure')measure(b.dataset.date);
    else if(a==='plates')plates();
    else if(a==='finish')finishWorkout();
    else if(a==='reopen'){delete s.finishedAt;delete s.partial;commit(s);render();}
    else if(a==='check-set'){
      const entry=s.snapshot.find(e=>e.id===id),r=s.exercises[id],x=r.sets[+b.dataset.index];
      if(x.complete){x.complete=false;r.done=false;commit(s);replaceExercise(id);return;}
      const error=T.setError(x,entry,state.config);if(error){$('#error-'+id).textContent=error;return;}
      x.complete=true;r.done=r.sets.every(x=>x.complete);commit(s);replaceExercise(id);if(state.config.autoRest&&s.date===T.today())startRest(entry.rest,entry.name);
    }
    else if(a==='add-set'){if(s.exercises[id].sets.length>=10){toast('Keep this movement to 10 working sets or fewer.');return;}s.exercises[id].sets.push({w:'',r:'',rir:'',complete:false});s.exercises[id].done=false;commit(s);replaceExercise(id);}
    else if(a==='apply-load'){s.exercises[id].sets.forEach(x=>{if(!x.complete&&x.w==='')x.w=b.dataset.weight;});commit(s);replaceExercise(id);}
    else if(a==='rest'){const e=s.snapshot.find(x=>x.id===id);if(s.date===T.today())startRest(e.rest,e.name);else toast('Rest timers run for today’s workout.');}
    else if(a==='timer-stop')stopRest();
    else if(a==='timer-add'&&timer){timer.end=Math.max(Date.now(),timer.end)+30000;timer.total+=30;timer.fired=false;state.config.activeTimer=timer;save();wake();tick();}
    else if(a==='swap')swap(id);
    else if(a==='choose-swap'){
      const from=b.dataset.from,idx=s.snapshot.findIndex(e=>e.id===from),ex=E[id],target=s.snapshot[idx].target;
      s.snapshot[idx]={id,name:ex.name,target,range:ex.range.slice(),rest:ex.rest,unit:ex.unit};s.exercises[id]={sets:Array.from({length:target},()=>({w:'',r:'',rir:'',complete:false})),done:false,skipped:false};delete s.exercises[from];commit(s);closeModal();render();toast('Movement swapped for this workout.');
    }
    else if(a==='skip'){modal('Listen to your session.','SKIP '+esc(E[id]?.name||id),`<p class="muted">Keep a reason so your coach review has context. Any completed sets will be kept in your log.</p><div class="button-row spaced">${['Pain','No time','Equipment','Tired'].map(reason=>btn(reason,'skip-reason','secondary',`data-id="${esc(id)}" data-reason="${reason}"`)).join('')}</div>`);}
    else if(a==='skip-reason'){const r=s.exercises[id];r.skipped=true;r.skipReason=b.dataset.reason;r.pain=b.dataset.reason==='Pain';r.done=false;commit(s);closeModal();replaceExercise(id);if(r.pain)toast('Stop this movement. Seek qualified advice for persistent or concerning pain.');}
    else if(a==='unskip'){s.exercises[id].skipped=false;commit(s);replaceExercise(id);}
    else if(a==='backup')backup();
    else if(a==='raw-backup'){try{download(localStorage.getItem(storageKey)||'',`iron-logbook-original-${T.today()}.txt`,'text/plain');}catch{toast('Browser access is blocked.');}}
    else if(a==='copy-backup'){if(!navigator.clipboard){toast('Clipboard unavailable. Use Backup JSON.');return;}navigator.clipboard.writeText(JSON.stringify(exportPayload(),null,2)).then(()=>toast('Backup copied. Paste it somewhere safe.')).catch(()=>toast('Clipboard unavailable. Use Backup JSON.'));}
    else if(a==='import')$('#import-file').click();
    else if(a==='csv')csv();else if(a==='report')report();else if(a==='calendar')calendar();
  });
  document.addEventListener('input',event=>{
    const input=event.target;
    if(input.id==='exercise-search'){query=input.value;$('#library-results').innerHTML=libraryResults();}
    else if(input.dataset.set){const s=currentSession(),x=s?.exercises[input.dataset.id]?.sets[+input.dataset.index];if(x){x[input.dataset.set]=input.value.trim();x.complete=false;commit(s);}}
    else if(input.id==='session-notes'){const s=currentSession();s.notes=input.value;commit(s);}
    else if(input.id==='coach-notes'){state.config.coachNotes=input.value;save();}
  });
  document.addEventListener('change',event=>{
    const input=event.target;
    if(input.id==='equipment-filter'){onlyAvailable=input.checked;$('#library-results').innerHTML=libraryResults();}
    else if(input.id==='favorite-filter'){favoritesOnly=input.checked;$('#library-results').innerHTML=libraryResults();}
    else if(input.id==='chart-exercise'){chartExercise=input.value;render();}
    else if(input.id==='import-file')importFile(input.files[0]);
    else if(input.id==='measure-date'){if(T.validDate(input.value))measure(input.value);}
  });
  document.addEventListener('submit',event=>{
    event.preventDefault();const form=event.target,data=new FormData(form);
    if(form.id==='settings-form'){
      const days=data.getAll('days').map(Number);if(days.length<2||days.length>4){$('#settings-error').textContent='Choose between two and four training days.';return;}
      const updated=T.clone(state.config);Object.assign(updated,{name:String(data.get('name')).trim(),goal:data.get('goal'),experience:data.get('experience'),duration:+data.get('duration'),start:data.get('start'),days,autoRest:data.has('autoRest'),setup:true});
      for(const k of ['barWeight','maxLoad','increment','attachmentMax','dumbbellMax','verticalMax']){const raw=data.get(k),v=T.number(raw);if(raw!==''&&(v===null||v<=0||v>1000)){ $('#settings-error').textContent='Equipment values must be positive numbers, or left blank.';return;}updated[k]=v;}
      if(updated.maxLoad!==null&&updated.barWeight!==null&&updated.maxLoad<updated.barWeight){$('#settings-error').textContent='The loaded bar limit must be at least the empty bar weight.';return;}
      if(updated.verticalMax>15){$('#settings-error').textContent='This Domyos kit is limited to 15 kg in vertical grip.';return;}
      Object.keys(EQUIPMENT).forEach(k=>updated.equipment[k]=data.has('gear-'+k));state.config=updated;save();nav('plan');toast('Your plan is updated. Existing workout logs keep their original exercises.');
    }else if(form.id==='readiness-form'){
      if(data.get('readiness')==='pain'){$('#readiness-error').textContent='Pause training when you feel pain. Reassess the movement and get qualified advice if it persists. You can close this check-in and return when you feel ready.';return;}
      const s=T.newSession(state,T.today(),pendingPlan);s.readiness=data.get('readiness');commit(s);closeModal();nav('workout/'+s.date);
    }else if(form.id==='finish-form'){
      const s=currentSession();s.partial=!T.completeSession(s);s.finishedAt=Date.now();s.effort=data.get('effort');s.notes=data.get('notes');if(data.has('pain')){s.readiness='pain';s.snapshot.forEach(e=>{if(s.exercises[e.id].sets.some(x=>x.complete))s.exercises[e.id].pain=true;});}commit(s);stopRest();const t=T.totals(s);render();modal('You showed up. That counts.','WORKOUT SAVED',`<div class="end-result"><span class="insight-icon">${icon('check')}</span><h2>${s.partial?'Partial session saved':'Session complete'}</h2><p class="muted spaced">${t.sets} working sets · ${fmt(t.volume)} kg volume</p><p class="muted small spaced">Your numbers and notes are ready in Progress and Coach review.</p><div class="button-row spaced" style="justify-content:center">${btn('See my progress','show-progress')}${btn('Back to overview','today','secondary')}</div></div>`);
      $('#dialog-content [data-action="show-progress"]').onclick=()=>{closeModal();nav('progress');};
    }else if(form.id==='measure-form'){
      const d=data.get('date'),bw=String(data.get('bw')).trim(),waist=String(data.get('waist')).trim();
      if(!T.validDate(d)||d>T.today()||(!bw&&!waist)||[bw,waist].some(x=>x!==''&&(T.number(x)===null||T.number(x)<=0||T.number(x)>500))){$('#measure-error').textContent='Enter a valid date and at least one positive measurement (up to 500).';return;}
      const m=d.slice(0,7),day=String(T.date(d).getDate());state.metrics[m]??={month:m,days:{}};state.metrics[m].days[day]={bw:bw.replace(',','.'),waist:waist.replace(',','.'),updatedAt:Date.now()};save();closeModal();if(route==='progress')render();else nav('progress');toast('Body check-in saved.');
    }else if(form.id==='plate-form'){
      const total=T.number(data.get('total'));if(total===null){$('#plate-result').innerHTML='<div class="notice danger">Enter a valid target weight.</div>';return;}
      const kind=data.get('kind'),result=T.plateLoad(total,kind,state.config);$('#plate-result').innerHTML=result.error?`<div class="notice danger">${esc(result.error)}</div>`:`<div class="notice green"><strong>${fmt(total)} kg ${kind==='pair'?'per dumbbell':'total'}</strong><br>On each end${kind==='pair'?' of each dumbbell':''}: ${result.plates.map(p=>p.count+' × '+p.size+' kg').join(' + ')||'no plates'}<br><small>${fmt(result.base)} kg ${kind==='pair'?'handle':'bar'} + ${fmt(total-result.base)} kg plates</small></div>`;
    }
  });
  $('#dialog').addEventListener('close',()=>{stopAnimation();if(modalOpener?.isConnected)modalOpener.focus();});
  $('#dialog').addEventListener('click',event=>{if(event.target===$('#dialog')){const rect=$('#dialog').getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)closeModal();}});
  window.addEventListener('hashchange',()=>{if($('#dialog').open)closeModal();render();window.scrollTo(0,0);$('#main').focus({preventScroll:true});});
  window.addEventListener('pagehide',save);
  document.addEventListener('visibilitychange',()=>{if(document.hidden)save();else{if(timer)wake();tick();}});
  if(demo){const banner=document.createElement('div');banner.className='demo-banner';banner.innerHTML='Demo space · Sample data, separate from your personal log. <a href="./#today">Return to my log</a>';$('.workspace').prepend(banner);}
  if(state.config.activeTimer&&Number.isFinite(state.config.activeTimer.end)&&state.config.activeTimer.end>Date.now()-60000){timer=state.config.activeTimer;tick();}
  setInterval(tick,500);render();
  const localPreview=['localhost','127.0.0.1','[::1]'].includes(location.hostname);
  if('serviceWorker' in navigator&&(!localPreview||new URLSearchParams(location.search).has('offline'))){navigator.serviceWorker.register('sw.js').then(reg=>{reg.addEventListener('updatefound',()=>{reg.installing?.addEventListener('statechange',()=>{if(reg.waiting)toast('An app update is ready. Close all app tabs and reopen to use it.');});});}).catch(()=>{});}
})();
